Update Build firmware.yml

diff --git a/.github/workflows/Build firmware.yml b/.github/workflows/Build firmware.yml
--- a/.github/workflows/Build firmware.yml
+++ b/.github/workflows/Build firmware.yml
@@ -16,91 +16,83 @@ jobs:
     container: registry.gitlab.com/hadzhioglu/padavan-ng
     defaults: { run: { shell: bash } }
     steps:
-    - uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-    - name: Get variables
-      run: |
-        sed -i 's|\r$||g' variables build.config
-        . <(cat variables build.config)
-        PADAVAN_THEMES="${PADAVAN_THEMES[*]}"
-        for v in "${!PADAVAN_@}" "${!CONFIG_@}"; do
-          echo "$v=${!v}" >> $GITHUB_ENV
-        done
-
-    - name: Download sources and toolchain
-      run: |
-        git config --global --add safe.directory '*'
-        git clone -b "$PADAVAN_BRANCH" "$PADAVAN_REPO"
-        git -C padavan-ng checkout "$PADAVAN_COMMIT"
-        wget -qO- "$PADAVAN_TOOLCHAIN_URL" | tar -C padavan-ng --zstd -xf -
-
-    - name: Install themes
-      run: |
-        if [[ -n $PADAVAN_THEMES ]]; then
-          git clone --depth 1 -b "$PADAVAN_THEMES_BRANCH" "$PADAVAN_THEMES_REPO" themes
-          cp -r themes/common-theme themes/jquery.js padavan-ng/trunk/user/www/n56u_ribbon_fixed
-          for theme in $PADAVAN_THEMES; do
-            cp -r "themes/$theme-theme" padavan-ng/trunk/user/www/n56u_ribbon_fixed
+      - name: Get variables
+        run: |
+          sed -i 's|\r$||g' variables build.config
+          . <(cat variables build.config)
+          PADAVAN_THEMES="${PADAVAN_THEMES[*]}"
+          for v in "${!PADAVAN_@}" "${!CONFIG_@}"; do
+            echo "$v=${!v}" >> $GITHUB_ENV
           done
-        fi
 
-    - name: Run custom pre-build script
-      run: '[[ -f pre-build.sh ]] && . pre-build.sh || :'
+      - name: Download sources and toolchain
+        run: |
+          git config --global --add safe.directory '*'
+          git clone -b "$PADAVAN_BRANCH" "$PADAVAN_REPO"
+          git -C padavan-ng checkout "$PADAVAN_COMMIT"
+          wget -qO- "$PADAVAN_TOOLCHAIN_URL" | tar -C padavan-ng --zstd -xf -
 
-    - name: Build firmware
-      run: |
-        cp build.config padavan-ng/trunk/.config
-        pushd padavan-ng/trunk
-        ./clear_tree.sh
-        ./build_firmware.sh
-        popd
+      - name: Install themes
+        run: |
+          if [[ -n $PADAVAN_THEMES ]]; then
+            git clone --depth 1 -b "$PADAVAN_THEMES_BRANCH" "$PADAVAN_THEMES_REPO" themes
+            cp -r themes/common-theme themes/jquery.js padavan-ng/trunk/user/www/n56u_ribbon_fixed
+            for theme in $PADAVAN_THEMES; do
+              cp -r "themes/$theme-theme" padavan-ng/trunk/user/www/n56u_ribbon_fixed
+            done
+          fi
 
-    - name: Run custom post-build script
-      run: '[[ -f post-build.sh ]] && . post-build.sh || :'
+      - name: Run custom pre-build script
+        run: '[[ -f pre-build.sh ]] && . pre-build.sh || :'
 
-    - name: Prepare artifacts
-      run: |
-        FW_FILE_NAME="$(find padavan-ng/trunk/images -type f -regextype posix-extended -iregex ".*\.(trx|bin)$" -printf "%T@\t%f\n" | sort -V | tail -1 | cut -f2)"
-        cp "padavan-ng/trunk/images/$FW_FILE_NAME" .
-        dd if=/dev/zero of=128kempty.bin bs=128k count=1
-        cat 128kempty.bin "$FW_FILE_NAME" > tp_recovery.bin
-        wget -O tftpd64.464.zip https://github.com/danayer/TP-Link-EC220-G5-v2.0-Padavan/releases/download/release-2025.04.22_02.07.51/tftpd64.464.zip
-        echo "FW_FILE_NAME=$FW_FILE_NAME" >> $GITHUB_ENV
-        echo "BUILD_TIMESTAMP=$(date '+%Y.%m.%d_%H.%M.%S')" >> $GITHUB_ENV
+      - name: Build firmware
+        run: |
+          cp build.config padavan-ng/trunk/.config
+          pushd padavan-ng/trunk
+          ./clear_tree.sh
+          ./build_firmware.sh
+          popd
 
-    - name: Upload artifacts
-      uses: actions/upload-artifact@v4
-      with:
-        name: padavan-ng_${{ env.CONFIG_VENDOR }}_${{ env.CONFIG_FIRMWARE_PRODUCT_ID }}_${{ env.BUILD_TIMESTAMP }}
-        retention-days: 7
-        path: |
-          ${{ env.FW_FILE_NAME }}
-          tp_recovery.bin
-          tftpd64.464.zip
+      - name: Run custom post-build script
+        run: '[[ -f post-build.sh ]] && . post-build.sh || :'
 
-    - name: Create Release
-      uses: softprops/action-gh-release@v2
-      with:
-        tag_name: release-${{ env.BUILD_TIMESTAMP }}
-        name: Padavan TP-Link EC220-G5 v2 (${{ env.BUILD_TIMESTAMP }})
-        files: |
-          ${{ env.FW_FILE_NAME }}
-          tp_recovery.bin
-          tftpd64.464.zip
-        body: |
-          ## 💝 Поддержать разработку
-          Если вам нравится прошивка, вы можете поддержать разработку:
-          - [Купить кофе](https://pay.cloudtips.ru/p/afb55f71)
-          - [Поддержать на Boosty](https://boosty.to/danayer)
+      - name: Prepare artifacts
+        run: |
+          FW_FILE_NAME="$(find padavan-ng/trunk/images -type f -regextype posix-extended -iregex ".*\.(trx|bin)$" -printf "%T@\t%f\n" | sort -V | tail -1 | cut -f2)"
+          cp "padavan-ng/trunk/images/$FW_FILE_NAME" .
+          dd if=/dev/zero of=128kempty.bin bs=128k count=1
+          cat 128kempty.bin "$FW_FILE_NAME" > tp_recovery.bin
+          wget -O tftpd64.464.zip https://github.com/danayer/TP-Link-EC220-G5-v2.0-Padavan/releases/download/release-2025.04.22_02.07.51/tftpd64.464.zip
+          echo "FW_FILE_NAME=$FW_FILE_NAME" >> $GITHUB_ENV
+          echo "BUILD_TIMESTAMP=$(date '+%Y.%m.%d_%H.%M.%S')" >> $GITHUB_ENV
 
-          📋 Инструкция прошивки и прочая информация...
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: firmware_files
+          path: |
+            ${{ env.FW_FILE_NAME }}
+            tp_recovery.bin
+            tftpd64.464.zip
 
-    - name: Check firmware size
-      run: |
-        partitions=padavan-ng/trunk/configs/boards/$CONFIG_VENDOR/$CONFIG_FIRMWARE_PRODUCT_ID/partitions.config
-        max_fw_size="$(awk '/Firmware/ { getline; getline; sub(",", ""); print strtonum($2); }' "$partitions")"
-        fw_size="$(stat -c %s "$FW_FILE_NAME")"
-        if ((fw_size > max_fw_size)); then
-          echo "Firmware size exceeds max size for your target device"
-          exit 1
-        fi
+      - name: Create Release
+        uses: softprops/action-gh-release@v2
+        with:
+          tag_name: release-${{ env.BUILD_TIMESTAMP }}
+          name: Firmware ${{ env.BUILD_TIMESTAMP }}
+          files: |
+            ${{ env.FW_FILE_NAME }}
+            tp_recovery.bin
+            tftpd64.464.zip
+
+      - name: Check firmware size
+        run: |
+          partitions=padavan-ng/trunk/configs/boards/$CONFIG_VENDOR/$CONFIG_FIRMWARE_PRODUCT_ID/partitions.config
+          max_fw_size="$(awk '/Firmware/ { getline; getline; sub(",", ""); print strtonum($2); }' "$partitions")"
+          fw_size="$(stat -c %s "$FW_FILE_NAME")"
+          if ((fw_size > max_fw_size)); then
+            echo "Error: Firmware size exceeds limit"
+            exit 1
+          fi
